[package]
name = "playback"
description = "a simple workflow manager"
license = "MIT"
repository = "https://github.com/Primiti-ve/playback"
readme = "../README.md"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "pb"
path = "src/main.rs"

[dependencies]
miniclap = { version = "0.1.1" }

# internal
playback-lib = { path = "../lib", version = "0.1.0" }
playback-logger = { path = "../crates/logger", version = "0.1.0" }
