[package]
name = "playback-lib"
description = "the core utilities for playback"
license = "MIT"
repository = "https://github.com/Primiti-ve/playback"
readme = "README.md"
version = "0.1.0"
edition = "2024"

[dependencies]

# internal
playback-dsl = { path = "../crates/dsl", version = "0.1.0" }
playback-logger = { path = "../crates/logger", version = "0.1.0" }
