[package]
name = "playback-lib"
description = "a simple workflow manager"
license = "MIT"
repository = "https://github.com/Primiti-ve/playback"
readme = "README.md"
version = "0.1.0"
edition = "2024"

[dependencies]

# workspace
clap = { workspace = true }
log = { workspace = true }

# internal
playback-toml = { path = "../crates/toml", version = "0.1.0" }
