name = "conditions"
description = "shows off the conditions feature"
version = "0.1.0"
author = "primiti_ve"

[workflow.env]
shell = "pwsh"

[workflow.arguments.message]
name = "title"
type = "positional"
required = true

[workflow.arguments.description]
name = "description"
type = "positional"
required = true

[workflow.steps.step1]
command = "echo"
arguments = ['{{title}}']
order = 1

[workflow.steps.step2]
command = "echo"
arguments = {
    if description != "" {
        ["{{description}}"]
    } else {
        ["no description..."]
    }
}
order = 2
